try:
    print(2/2)
except Exception as e:
    print("error: ", e)
finally:
    print("Process Ended")
    